FROM facette/buildenv:stretch-amd64

LABEL maintainer="Development Team <dev@facette.io>"

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --no-install-recommends -t stretch-backports -y \
        crossbuild-essential-armhf \
        librrd-dev:armhf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CC=arm-linux-gnueabihf-gcc GOARCH=arm

# vim: ft=dockerfile ts=4 sw=4 et
