FROM facette/build:stretch-amd64

MAINTAINER Development Team <dev@facette.io>

RUN dpkg --add-architecture armel && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
        libc6-dev:armel \
        linux-libc-dev:armel \
        librrd-dev:armel \
        crossbuild-essential-armel && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV CC=arm-linux-gnueabi-gcc GOARCH=arm

# vim: ft=dockerfile ts=4 sw=4 et
